name: ml 
dependencies:
        - absl-py=0.6.1
        - asn1crypto=0.24.0
        - astor=0.7.1
        - certifi=2018.1.18
        - chardet=3.0.4
        - cryptography
        - cycler=0.10.0
        - decorator=4.1.2
        - gast=0.2.0
        - grpcio
        - h5py=2.8.0
        - idna=2.6
        - ipykernel=5.1.0
        - ipython=5.5.0
        - Keras=2.2.4
        - Keras-Applications=1.0.6
        - Keras-Preprocessing=1.0.5
        - keyrings.alt=3.0
        - kiwisolver=1.0.1
        - Mako=1.0.7
        - Markdown=3.0.1
        - MarkupSafe=1.0
        - matplotlib
        - numpy=1.15.4
        - olefile=0.45.1
        - pandas=0.23.4
        - pexpect=4.2.1
        - pickleshare=0.7.4
        - Pillow=5.1.0
        - pip=19.0.1
        - protobuf=3.6.1
        - pycrypto=2.6.1
        - Pygments=2.2.0
        - pyparsing=2.3.0
        - python=3.6.7
        - pytz=2018.3
        - PyYAML=3.12
        - pyzmq=17.1.2
        - reportlab=3.4.0
        - requests=2.18.4
        - scikit-learn=0.20.1
        - scipy=1.1.0
        - setuptools=39.0.1
        - simplegeneric=0.8.1
        - simplejson=3.13.2
        - six=1.11.0
        - tensorboard=1.12.0
        - tensorflow=1.12.0
        - termcolor=1.1.0
        - tornado=5.1.1
        - traitlets=4.3.2
        - urllib3=1.22
        - wcwidth=0.1.7
        - Werkzeug=0.14.1
        - wheel=0.30.0
        - zope.interface
        - pip:        
                - screen-resolution-extra
                - xkit=0.0.0
                - command-not-found=0.3
                - pyrfc3339=1.0
                - jupyter-client=5.2.3
                - httplib2=0.9.2
                - defer=1.0.6
                - macaroonbakery=1.1.3
                - keyring=10.6.0
                - python-dateutil=3.6.7
                - unattended-upgrades=0.1
                - ipython-genutils=0.2.0
                - python-debian=0.1.32
                - oauth=1.0.1
                - distro-info=0.18
                - brlapi=0.6.6
                - louis=3.5.0
                - pyxdg=0.25
                - system-service=0.3
                - pycups=1.9.73
                - pygobject=3.26.1
                - jupyter-core=4.4.0
                - systemd-python=234
                - pandas-ml=0.5.0
                - ssh-import-id=5.7
                - lazr.uri=1.0.3
                - lazr.restfulclient=0.13.5
                - language-selector=0.1
                - ufw=0.35
                - apturl=0.5.2
                - secretstorage=2.3.1
                - cupshelpers=1.0
                - pymacaroons=0.13.0
                - requests-unixsocket=0.1.5
                - netifaces=0.10.4
                - usb-creator=0.3.3
                - pynacl=1.1.2
                - wadllib=1.3.2
                - prompt-toolkit=1.0.15
                - python-apt=1.6.3+ubuntu1
                - ubuntu-drivers-common=0.0.0
                - launchpadlib=1.10.6
                - pycairo=1.16.2
                - sklearn=0.0
